import type { SceneEntry } from './scenes.registry';

import {
  AuthScene,
  CookScene,
  FavouritesScene,
  KitchenEmptyScene,
  KitchenScene,
  OfflineScene,
  OnboardingScene,
  RecipeScene,
  SettingsScene,
  SuggestionsEmptyScene,
  SuggestionsLoadingScene,
  SuggestionsScene,
} from './screens/core-scenes';
import {
  AddStockScene,
  CaptureRecoveryScene,
  EmptyKitchenScene,
  ExtractionReviewScene,
  KitchenDashboardScene,
  LabelCaptureScene,
  LowStockScene,
  MarketEmptyScene,
  MarketListScene,
  MarketModeScene,
  ShelfScanScene,
  StockDetailScene,
  StockHistoryScene,
  StockLocationScene,
  UploadReceiptScene,
  UseItUpScene,
} from './screens/kitchen-scenes';
import {
  ChatAboutMealScene,
  ChatErrorScene,
  ChatHistoryScene,
  ChatMealScene,
  ChatStockScene,
  ChatSubstitutionScene,
} from './screens/chat-scenes';
import {
  ConstraintsScene,
  MilestoneScene,
  MoodScene,
  NutritionScene,
  PlanToMarketScene,
  PortionsScene,
  RepeatsScene,
  ShouldEatScene,
  SpendScene,
  WeekEmptyScene,
  WeekPlanScene,
  WeekSummaryScene,
} from './screens/insight-scenes';
import {
  ConsoleAuditScene,
  ConsoleDashboardScene,
  ConsoleFeedbackEmptyScene,
  ConsoleFeedbackScene,
  ConsoleFlagsScene,
  ConsolePromptsScene,
  ConsoleRecipeEditorScene,
  ConsoleRecipesScene,
  ConsoleShellScene,
  ConsoleUsersScene,
} from './screens/console-scenes';
import { LandingScene } from './screens/site-scenes';

/**
 * Every scene, in sidebar order.
 *
 * Add an entry the moment a scene is built. Each is reachable at
 * `/scenes/<id>` and inside `/preview` under the Scenes group.
 */
export const SCENE_ENTRIES: readonly SceneEntry[] = [
  {
    id: 'kitchen',
    label: 'The kitchen',
    group: 'Core',
    spec: '310-scene-kitchen.html',
    summary: "The product's front door. Three ways in, one basket, one commit.",
    frames: ['phone', 'desktop'],
    Scene: KitchenScene,
  },
  {
    id: 'kitchen-empty',
    label: 'The kitchen — empty',
    group: 'Core',
    spec: '310-scene-kitchen.html',
    summary: 'Nothing added yet — the CTA is off and says why.',
    frames: ['phone', 'desktop'],
    Scene: KitchenEmptyScene,
  },
  {
    id: 'suggestions',
    label: 'Suggestions',
    group: 'Core',
    spec: '311-scene-suggestions.html',
    summary: 'Three meals, one decision. The weak match demotes its own CTA.',
    frames: ['phone', 'desktop'],
    Scene: SuggestionsScene,
  },
  {
    id: 'suggestions-loading',
    label: 'Suggestions — loading',
    group: 'Core',
    spec: '311-scene-suggestions.html',
    summary: 'The engine is running; skeletons mirror the cards they become.',
    frames: ['phone', 'desktop'],
    Scene: SuggestionsLoadingScene,
  },
  {
    id: 'suggestions-empty',
    label: 'Suggestions — empty',
    group: 'Core',
    spec: '311-scene-suggestions.html',
    summary: 'Nothing came back — and the way forward is offered.',
    frames: ['phone', 'desktop'],
    Scene: SuggestionsEmptyScene,
  },
  {
    id: 'recipe',
    label: 'The recipe',
    group: 'Core',
    spec: '312-scene-recipe.html',
    summary: 'What you have, what you need, one commit. Provenance sits on the photo.',
    frames: ['phone', 'desktop'],
    Scene: RecipeScene,
  },
  {
    id: 'cook',
    label: 'Cook mode',
    group: 'Core',
    spec: '313-scene-cook.html',
    summary: 'Hands busy, phone propped. No nav — leaving is a decision.',
    frames: ['phone', 'desktop'],
    Scene: CookScene,
  },
  {
    id: 'favourites',
    label: 'Favourites',
    group: 'Core',
    spec: '314-scene-favourites.html',
    summary: 'What was saved, with provenance intact.',
    frames: ['phone', 'desktop'],
    Scene: FavouritesScene,
  },
  {
    id: 'settings',
    label: 'Settings',
    group: 'Core',
    spec: '315-scene-settings.html',
    summary: 'Measures, what we send, and how AI is used — stated plainly.',
    frames: ['phone', 'desktop'],
    Scene: SettingsScene,
  },
  {
    id: 'onboarding',
    label: 'Onboarding',
    group: 'Core',
    spec: '316-scene-onboarding.html',
    summary: 'One screen. The trust claim is made before anything is asked.',
    frames: ['phone', 'desktop'],
    Scene: OnboardingScene,
  },
  {
    id: 'offline',
    label: 'Offline',
    group: 'Core',
    spec: '317-scene-offline.html',
    summary: 'Saved recipes still work, and each says how old it is.',
    frames: ['phone', 'desktop'],
    Scene: OfflineScene,
  },
  {
    id: 'auth',
    label: 'Sign in',
    group: 'Core',
    spec: '318-scene-auth.html',
    summary: 'Optional by design — you can cook without an account.',
    frames: ['phone', 'desktop'],
    Scene: AuthScene,
  },

  /* ---------- Standing kitchen ---------- */
  { id: 'kitchen-dashboard', label: 'Kitchen dashboard', group: 'Standing kitchen', spec: '330-scene-kitchen-dashboard.html', summary: 'What is in, what is low, and what was noticed.', frames: ['phone', 'desktop'], Scene: KitchenDashboardScene },
  { id: 'stock-location', label: 'Stock by location', group: 'Standing kitchen', spec: '331-scene-stock-location.html', summary: 'Fridge, shelf, freezer — grouped where things actually live.', frames: ['phone', 'desktop'], Scene: StockLocationScene },
  { id: 'low-stock', label: 'Running low', group: 'Standing kitchen', spec: '332-scene-low-stock.html', summary: 'Only what blocks a meal you cook often.', frames: ['phone', 'desktop'], Scene: LowStockScene },
  { id: 'add-stock', label: 'Add stock', group: 'Standing kitchen', spec: '333-scene-add-stock.html', summary: 'For correcting something — never for stock-taking.', frames: ['phone', 'desktop'], Scene: AddStockScene },
  { id: 'stock-detail', label: 'One thing', group: 'Standing kitchen', spec: '334-scene-stock-detail.html', summary: 'Everything that changed a count, and none of it typed in.', frames: ['phone', 'desktop'], Scene: StockDetailScene },
  { id: 'market-list', label: 'Market list', group: 'Standing kitchen', spec: '335-scene-market-list.html', summary: 'What to buy, and what each thing unblocks.', frames: ['phone', 'desktop'], Scene: MarketListScene },
  { id: 'market-mode', label: 'In the market', group: 'Standing kitchen', spec: '336-scene-market-mode.html', summary: 'Big targets, one hand, a bag in the other.', frames: ['phone'], Scene: MarketModeScene },
  { id: 'market-empty', label: 'Market list — empty', group: 'Standing kitchen', spec: '335-scene-market-list.html', summary: 'Nothing to buy — the good outcome, so no CTA.', frames: ['phone', 'desktop'], Scene: MarketEmptyScene },
  { id: 'use-it-up', label: 'Use these first', group: 'Standing kitchen', spec: '337-scene-use-it-up.html', summary: 'What is turning, and what would use it tonight.', frames: ['phone', 'desktop'], Scene: UseItUpScene },
  { id: 'stock-history', label: 'Kitchen history', group: 'Standing kitchen', spec: '338-scene-stock-history.html', summary: 'Every change, and where it came from.', frames: ['phone', 'desktop'], Scene: StockHistoryScene },
  { id: 'empty-kitchen', label: 'Empty kitchen', group: 'Standing kitchen', spec: '339-scene-empty-kitchen.html', summary: 'Camera first, and the skip always visible.', frames: ['phone', 'desktop'], Scene: EmptyKitchenScene },

  /* ---------- Capture ---------- */
  { id: 'shelf-scan', label: 'Photograph a shelf', group: 'Capture', spec: '341-scene-shelf-scan.html', summary: 'The multi-shot tray — more angles read better.', frames: ['phone', 'desktop'], Scene: ShelfScanScene },
  { id: 'upload-receipt', label: 'Upload a receipt', group: 'Capture', spec: '340-scene-upload-receipt.html', summary: 'The fastest way to fill a kitchen.', frames: ['phone', 'desktop'], Scene: UploadReceiptScene },
  { id: 'extraction-review', label: 'What we read', group: 'Capture', spec: '342-scene-extraction-review.html', summary: 'Reviewed, never auto-committed. Desktop shows the source photo.', frames: ['phone', 'desktop'], Scene: ExtractionReviewScene },
  { id: 'capture-recovery', label: 'Capture failed', group: 'Capture', spec: '343-scene-capture-recovery.html', summary: 'Typing offered as an equal, not a fallback.', frames: ['phone', 'desktop'], Scene: CaptureRecoveryScene },
  { id: 'permission', label: 'Camera permission', group: 'Capture', spec: '344-scene-label-capture.html', summary: 'Asked in context, with the reason, always skippable.', frames: ['phone', 'desktop'], Scene: LabelCaptureScene },

  /* ---------- Chat ---------- */
  { id: 'chat-meal', label: 'Ask about a meal', group: 'Chat', spec: '350-scene-chat-meal.html', summary: 'Answered from the kitchen, cited.', frames: ['phone', 'desktop'], Scene: ChatMealScene },
  { id: 'chat-stock', label: 'Ask about stock', group: 'Chat', spec: '351-scene-chat-stock.html', summary: 'The count, and what took it down.', frames: ['phone', 'desktop'], Scene: ChatStockScene },
  { id: 'chat-substitution', label: 'Ask for a swap', group: 'Chat', spec: '352-scene-chat-substitution.html', summary: 'General knowledge, labelled as the weakest source.', frames: ['phone', 'desktop'], Scene: ChatSubstitutionScene },
  { id: 'chat-error', label: 'Chat — failed', group: 'Chat', spec: '353-scene-chat-error.html', summary: 'A failure, and an honest "I do not know".', frames: ['phone', 'desktop'], Scene: ChatErrorScene },
  { id: 'chat-history', label: 'Chat history', group: 'Chat', spec: '354-scene-chat-history.html', summary: 'What you have asked before.', frames: ['phone', 'desktop'], Scene: ChatHistoryScene },
  { id: 'chat-about-meal', label: 'About one recipe', group: 'Chat', spec: '355-scene-chat-about-meal.html', summary: 'The recipe beside the conversation — desktop only.', frames: ['phone', 'desktop'], Scene: ChatAboutMealScene },

  /* ---------- Insights ---------- */
  { id: 'week-summary', label: 'Your week', group: 'Insights', spec: '360-scene-week-summary.html', summary: 'Seven days, and what was noticed — with the working shown.', frames: ['phone', 'desktop'], Scene: WeekSummaryScene },
  { id: 'week-empty', label: 'Your week — too early', group: 'Insights', spec: '360-scene-week-summary.html', summary: 'Under four meals, anything said would be a guess.', frames: ['phone', 'desktop'], Scene: WeekEmptyScene },
  { id: 'should-eat', label: 'What should I eat?', group: 'Insights', spec: '361-scene-should-eat.html', summary: 'An observation, then what would answer it.', frames: ['phone', 'desktop'], Scene: ShouldEatScene },
  { id: 'nutrition', label: 'Roughly, this week', group: 'Insights', spec: '362-scene-nutrition.html', summary: 'Estimates, labelled as estimates.', frames: ['phone', 'desktop'], Scene: NutritionScene },
  { id: 'repeats', label: 'Your repeats', group: 'Insights', spec: '363-scene-repeats.html', summary: 'What you cook most — worth knowing, not worth fixing.', frames: ['phone', 'desktop'], Scene: RepeatsScene },
  { id: 'spend', label: 'What you spent', group: 'Insights', spec: '364-scene-spend.html', summary: 'Roughly, and it says so twice.', frames: ['phone', 'desktop'], Scene: SpendScene },
  { id: 'milestone', label: 'A milestone', group: 'Insights', spec: '365-scene-milestone.html', summary: 'States a fact and stops. No points, no levels.', frames: ['phone', 'desktop'], Scene: MilestoneScene },

  /* ---------- Planning ---------- */
  { id: 'mood', label: 'What do you feel like?', group: 'Planning', spec: '370-scene-mood.html', summary: 'The taste-led door. Picking nothing is valid.', frames: ['phone', 'desktop'], Scene: MoodScene },
  { id: 'constraints', label: 'What to leave out', group: 'Planning', spec: '371-scene-constraints.html', summary: 'Hard filters — these remove results.', frames: ['phone', 'desktop'], Scene: ConstraintsScene },
  { id: 'week-plan', label: 'This week', group: 'Planning', spec: '372-scene-week-plan.html', summary: 'Seven slots, designed empty-first.', frames: ['phone', 'desktop'], Scene: WeekPlanScene },
  { id: 'plan-to-market', label: 'Plan to market list', group: 'Planning', spec: '373-scene-plan-to-market.html', summary: 'What the plan needs, minus what you have.', frames: ['phone', 'desktop'], Scene: PlanToMarketScene },
  { id: 'portions', label: 'Cooking for how many?', group: 'Planning', spec: '374-scene-portions.html', summary: 'Scaled, and it states what it scaled from.', frames: ['phone', 'desktop'], Scene: PortionsScene },

  /* ---------- Console ---------- */
  { id: 'console-shell', label: 'The console shell', group: 'Console', spec: 'a01-shell.html', summary: 'One wrapper class resolves the whole COUNTER register.', frames: ['desktop'], Scene: ConsoleShellScene },
  { id: 'console-dashboard', label: 'Dashboard', group: 'Console', spec: 'a02-dashboard.html', summary: 'Five numbers, and the one that costs money.', frames: ['desktop'], Scene: ConsoleDashboardScene },
  { id: 'console-recipes', label: 'Recipes', group: 'Console', spec: 'a03-recipes.html', summary: 'The table the curator never had — the shipped app has zero table markup.', frames: ['desktop'], Scene: ConsoleRecipesScene },
  { id: 'console-recipe-editor', label: 'Recipe editor', group: 'Console', spec: 'a04-recipe-editor.html', summary: 'Publishing is platform-wide, so it asks first.', frames: ['desktop'], Scene: ConsoleRecipeEditorScene },
  { id: 'console-audit', label: 'AI audit', group: 'Console', spec: 'a05-ai-audit.html', summary: 'Went in, came out, what it cost. Accountable rather than magic.', frames: ['desktop'], Scene: ConsoleAuditScene },
  { id: 'console-prompts', label: 'Prompt editor', group: 'Console', spec: 'a06-prompts.html', summary: 'The highest-gravity surface, with the diff and guard it never had.', frames: ['desktop'], Scene: ConsolePromptsScene },
  { id: 'console-users', label: 'Users', group: 'Console', spec: 'a07-users.html', summary: 'Suspending is an act on a person — typed confirmation.', frames: ['desktop'], Scene: ConsoleUsersScene },
  { id: 'console-feedback', label: 'Feedback queue', group: 'Console', spec: 'a08-feedback.html', summary: 'The flag beside the step it is about.', frames: ['desktop'], Scene: ConsoleFeedbackScene },
  { id: 'console-feedback-empty', label: 'Feedback — clear', group: 'Console', spec: 'a08-feedback.html', summary: 'An empty queue is the good outcome, so no CTA.', frames: ['desktop'], Scene: ConsoleFeedbackEmptyScene },
  { id: 'console-flags', label: 'Feature flags', group: 'Console', spec: 'a09-flags.html', summary: 'Each switch states what turning it off actually does.', frames: ['desktop'], Scene: ConsoleFlagsScene },

  /* ---------- Site ---------- */
  { id: 'landing', label: 'The landing page', group: 'Site', spec: 's90-scene-landing.html', summary: 'Every section composed, with the trust proof rendered by the real meal card.', frames: ['phone', 'desktop'], Scene: LandingScene },
];
