/**
 * The status contract — 39 named states, one vocabulary.
 *
 * Visual spec: design-system/projects/kinnijije-v2/preview/126-status-contract.html
 *              …through 143-status-measurement.html
 *
 * ## The failure this replaces
 *
 * The shipped app had **no status component at all** — 13 pill call-sites, 11 of
 * them inline ternaries, mapping 39 named database states onto a 7-value trust
 * and difficulty vocabulary. Measured collisions:
 *
 * | Old tone   | Meanings it carried                                          |
 * |------------|--------------------------------------------------------------|
 * | `easy`     | published · active user · AI call ok · feedback reviewed — 4  |
 * | `warn`     | draft · suspended · AI error · feedback target kind — 4       |
 * | `verified` | seed recipe · admin role · current prompt version — 3         |
 * | `medium`   | non-admin role · open feedback — 2, opposite valence          |
 *
 * ## The fix
 *
 * **Colour comes from the semantic enum. The word comes from the domain.** A
 * recipe is *Published*, not *easy*. A user is *Suspended*, not *warn*.
 *
 * One entry per lifecycle family, every named state spelled out, so a mapping
 * can never be invented at a call site again. There is deliberately no `tone`
 * prop on `Status` — a call site may never choose the colour.
 *
 * **Sky may never appear in a status.** Sky is the action colour; a blue badge
 * invites a press. Checkable: grep this file for `sky`.
 */

/** The five semantic tones, plus provenance — which is NOT a severity. */
export type StatusTone = 'neutral' | 'info' | 'success' | 'caution' | 'critical' | 'ai';

export interface StatusValue {
  /** The rendered word. Owned here — no screen renders the raw enum. */
  readonly label: string;
  readonly tone: StatusTone;
  /** When this value applies. Shown in the specimen, not in the product. */
  readonly when: string;
}

export type StatusFamily = Record<string, StatusValue>;

export const STATUS_REGISTRY = {
  /**
   * The product's whole trust proposition, in one pill. In the shipped app the
   * same recipe read "✓ Verified", "Verified recipe" and "✓ Verified" on three
   * consecutive screens — the label string is owned HERE so that cannot recur.
   *
   * AI uses grape, NOT caution: being machine-made is not a warning.
   */
  'recipe-source': {
    seed: {
      label: '✓ Verified',
      tone: 'success',
      when: "Written and tested by a person. The seed — the product's moat.",
    },
    ai: {
      label: '◆ Made by AI',
      tone: 'ai',
      when: 'Generated by a model. Quantities are estimates.',
    },
  },

  /** The publish gate. Publishing is a platform-wide act. */
  recipe: {
    published: { label: 'Published', tone: 'success', when: 'Live. Suggestable to every cook.' },
    draft: {
      label: 'Draft',
      tone: 'caution',
      when: 'Not suggestable. Visible only in the console.',
    },
  },

  /**
   * The image provenance the schema models and the app never showed. A cook
   * could be looking at an AI-generated image beside a Verified badge with no
   * way to tell. A generated image ALWAYS carries its tag.
   */
  'hero-image': {
    photo: { label: 'Photo', tone: 'success', when: 'A real photograph of the dish.' },
    ai_image: { label: 'AI image', tone: 'ai', when: 'Generated by a model. Always labelled.' },
    placeholder: {
      label: 'Placeholder',
      tone: 'neutral',
      when: "The dish family's mark. Honest about being a stand-in.",
    },
  },

  /** Recipe effort. NOT the user's preference — see `difficulty-floor`. */
  difficulty: {
    easy: { label: 'Easy', tone: 'neutral', when: '30 minutes, few steps.' },
    medium: { label: 'Medium', tone: 'info', when: 'About an hour, some technique.' },
    involved: { label: 'Involved', tone: 'caution', when: 'A project. Long, or many stages.' },
  },

  /**
   * The USER preference, kept deliberately separate from recipe difficulty —
   * `anything` has no recipe equivalent and `involved` has no preference
   * equivalent. Settings may never print the raw `anything`.
   */
  'difficulty-floor': {
    easy: { label: 'Keep it easy', tone: 'neutral', when: 'Only easy recipes.' },
    medium: { label: 'Medium is fine', tone: 'info', when: 'Easy and medium.' },
    anything: {
      label: 'Anything goes',
      tone: 'success',
      when: 'No floor — everything is offered.',
    },
  },

  /** The 0.6 threshold lives HERE, not hard-coded in a feature file. */
  match: {
    nothing_to_buy: {
      label: 'Nothing to buy',
      tone: 'success',
      when: 'Every ingredient is in the basket.',
    },
    strong_match: {
      label: 'Strong match',
      tone: 'info',
      when: 'Missing one or two small things.',
    },
    needs_a_shop: {
      label: 'Needs a shop',
      tone: 'caution',
      when: 'Under 60% of ingredients on hand.',
    },
  },

  /** Derived from source — never passed separately, so they cannot disagree. */
  approximate: {
    exact: { label: 'Exact', tone: 'success', when: 'A tested quantity from a seed recipe.' },
    approximate: {
      label: 'Approximate',
      tone: 'caution',
      when: 'An AI estimate. Rendered with ≈ and padded.',
    },
  },

  /**
   * The one place green is allowed to mean something other than success.
   * `need` is NEUTRAL, never critical — missing an ingredient is not an error.
   */
  'have-need': {
    you_have_it: { label: 'You have it', tone: 'success', when: 'Matched against the basket.' },
    you_need_it: {
      label: 'You need it',
      tone: 'neutral',
      when: 'Not in the basket. Grey, not red — shopping is not a failure.',
    },
    maybe: {
      label: 'Maybe',
      tone: 'caution',
      when: 'An uncertain match from a photo extraction.',
    },
  },

  /** Suspending is a consequential act on a person — hence critical. */
  user: {
    active: { label: 'Active', tone: 'success', when: 'Can sign in and cook.' },
    suspended: {
      label: 'Suspended',
      tone: 'critical',
      when: 'Cannot sign in. Their saved recipes are kept.',
    },
  },

  /** BOTH values always render — a missing badge is not a value. */
  role: {
    admin: {
      label: 'Admin',
      tone: 'info',
      when: 'Full console access. Can publish, edit prompts and suspend.',
    },
    user: { label: 'User', tone: 'neutral', when: 'The cook. No console access.' },
  },

  /** A correction offered in good faith is not an incident. */
  feedback: {
    open: { label: 'Open', tone: 'info', when: 'Waiting for a curator.' },
    reviewed: { label: 'Reviewed', tone: 'neutral', when: 'Handled. Kept for the record.' },
  },

  /** Neutral, because a helpful correction is not a warning. */
  'feedback-target': {
    step: { label: 'Step', tone: 'neutral', when: 'A cooking instruction is wrong.' },
    ingredient: { label: 'Ingredient', tone: 'neutral', when: 'A quantity or an item is wrong.' },
  },

  /** `generate` is caution-toned because it is the cost driver, not a failure. */
  'ai-kind': {
    vision: { label: 'Vision', tone: 'info', when: 'Read a kitchen photo.' },
    whisper: { label: 'Whisper', tone: 'info', when: 'Transcribed a voice note.' },
    parse: {
      label: 'Parse',
      tone: 'neutral',
      when: 'Turned text into an ingredient list. Cheapest.',
    },
    generate: {
      label: 'Generate',
      tone: 'caution',
      when: 'Wrote a whole recipe. The expensive one.',
    },
  },

  'ai-result': {
    ok: { label: 'OK', tone: 'success', when: 'Returned and parsed.' },
    error: {
      label: 'Error',
      tone: 'critical',
      when: 'Failed, timed out, or returned unparseable output.',
    },
  },

  extraction: {
    photo: { label: 'Photo', tone: 'info', when: 'One or more images, read by Vision.' },
    voice: { label: 'Voice', tone: 'info', when: 'A voice note, transcribed then parsed.' },
  },

  /** The state is SHOWN, not implied by a toggle position. */
  flag: {
    on: { label: 'On', tone: 'success', when: 'Live for every user.' },
    off: {
      label: 'Off',
      tone: 'neutral',
      when: 'Disabled. The affected surface shows a locked state, not an error.',
    },
  },

  /** The third value is the PRD's — as Nigerians measure. */
  measurement: {
    metric: { label: 'Metric', tone: 'neutral', when: 'Grams, millilitres.' },
    imperial: { label: 'Imperial', tone: 'neutral', when: 'Ounces, cups.' },
    as_we_measure: {
      label: 'As we measure',
      tone: 'info',
      when: 'Derica, cup, wrap, paint rubber.',
    },
  },
} as const satisfies Record<string, StatusFamily>;

export type StatusKind = keyof typeof STATUS_REGISTRY;

/** Every value a given family accepts. */
export type StatusValueOf<K extends StatusKind> = keyof (typeof STATUS_REGISTRY)[K] & string;

/** The tone classes. Note: no `sky` anywhere — sky acts, it never reports. */
export const STATUS_TONE_CLASS: Record<StatusTone, string> = {
  neutral: 'bg-neutral-soft text-neutral-onsoft border-neutral-border',
  info: 'bg-info-soft text-info-onsoft border-info-border',
  success: 'bg-success-soft text-success-onsoft border-success-border',
  caution: 'bg-caution-soft text-caution-onsoft border-caution-border',
  critical: 'bg-critical-soft text-critical-onsoft border-critical-border',
  // Outside the enum: provenance, not severity.
  ai: 'bg-grape-soft text-grape-onsoft border-grape-border',
};

export const STATUS_DOT_CLASS: Record<StatusTone, string> = {
  neutral: 'bg-neutral',
  info: 'bg-info',
  success: 'bg-success',
  caution: 'bg-caution',
  critical: 'bg-critical',
  ai: 'bg-grape',
};

/** Every family name, for the specimen gallery. */
export const STATUS_KINDS = Object.keys(STATUS_REGISTRY) as StatusKind[];
